### ISSUE TITLE
Does this repository support batch_size > 1?

### ISSUE THREAD

**Issue by zhaosheng-thu** [jjihwan/SV3D-fine-tune#2]
Thanks for your work! 
I'm wondering whether I can choose a batch_size > 1 in the data config during the finetuning procedure. Thanks.

**Comment by jjihwan** [comment]
Thank you for your interest.
Since my GPU (A6000) cannot handle bsz > 1 due to VRAM constraints, I didn’t address that case.
You might need to slightly modify the code to make it work well if it doesn’t currently.

**Comment by zhaosheng-thu** [comment]
> Thank you for your interest. Since my GPU (A6000) cannot handle bsz > 1 due to VRAM constraints, I didn’t address that case. You might need to slightly modify the code to make it work well if it doesn’t currently.

Thanks for your prompt reply.
I have tried a bs > 1, and I find that the conditioner ConcatTimestepEmbedderND will return a Tensor with a wrong shape. So for this repository, it currently doesn't support bs > 1. Closed.

**Comment by guiyuanyuanbao** [comment]
> > Thank you for your interest. Since my GPU (A6000) cannot handle bsz > 1 due to VRAM constraints, I didn’t address that case. You might need to slightly modify the code to make it work well if it doesn’t currently.感谢您的关注。由于 VRAM 限制，我的 GPU (A6000) 无法处理 bsz > 1，因此我没有解决这种情况。如果当前无法正常工作，您可能需要稍微修改代码以使其正常工作。
> 
> Thanks for your prompt reply.感谢您的及时回复。 I have tried a bs > 1, and I find that the conditioner ConcatTimestepEmbedderND will return a Tensor with a wrong shape. So for this repository, it currently doesn't support bs > 1. Closed.我尝试过 bs > 1，我发现调节器 ConcatTimestepEmbedderND 将返回形状错误的张量。因此，对于此存储库，它当前不支持 bs > 1. 已关闭。

I have reviewed the training code, and during the inference process, there is a part where B*T is noted to have a tensor shape of [21, xx...]. I apologize for not remembering the subsequent dimensions. In my understanding, in conjunction with a closed issue (https://github.com/jjihwan/SV3D-fine-tune/issues/2#issue-2350909425), I believe that after a single image generates a latent, the latents from 21 images are merged into a shape of [21, xx...]. In my understanding, the issue discussed in the aforementioned issue is also caused by this step. Due to certain reasons, I have not actually run this code, so I am not certain if my deduction is entirely correct.
