### ISSUE TITLE
想请教一下关于自定义数据的微调问题

### ISSUE THREAD

**Issue by ys830** [jjihwan/SV3D-fine-tune#7]
大佬您好！非常感谢你的分享~

目前我想在自己的医学图像数据集上用sv3d_u微调，但是在数据输入格式上还有一些困惑。我的数据为心脏在不同视角下的成像，有不同视角的外参信息。

参考您提供的输入，请问训练数据应该是每个视角的图像，经过 SVD的encoder，保存成一个.pt文件吗？还是说.pt文件是由视频生成的？是在代码的什么地方使用到了位置信息呢

您提供的方法是否相当于自己重新训练一下sv3d呢，因为我目前对这部分的理解还不是特别深入，期待您的回复~

**Comment by jjihwan** [comment]
Sorry, I'm Korean
Could you ask in English?

**Comment by ys830** [comment]
> Sorry, I'm Korean Could you ask in English?

Oh Sorry, thank you so much for your sharing!

Currently, I want to fine-tune sv3d_u on my own medical image dataset, but I am a bit confused about the data input format. My data consists of heart imaging from different perspectives, and there are extrinsic parameters for each view.

Based on the input format you provided, should the training data be the images from each perspective, passed through the SVD encoder, and then saved as a .pt file? Or is the .pt file generated from a video? Where is the information of the extrinsic parameters used in the code?

Is your method equivalent to retraining sv3d from scratch? I am still trying to deepen my understanding of this part, and I look forward to your response.Thanks~

**Comment by jjihwan** [comment]
No problem, thank you for your interest.

1. Extrinsic parameter
In my code, I used fixed elevation, azimuths and polars since all datapoints are captured in same location in my case.
The part is hard-coded in [here](https://github.com/jjihwan/SV3D-fine-tune/blob/559c4a8abe31e59d5a31ca0d34d47d7c422fc551/sgm/data/dataset.py#L109)
But you can inject the camera information by modifying [get_item function](https://github.com/jjihwan/SV3D-fine-tune/blob/559c4a8abe31e59d5a31ca0d34d47d7c422fc551/sgm/data/dataset.py#L145) and removing hard-coded part in the above.

2. pt file
All pt files are passed through the SVD encoder. You can refer "Notes" in the README.

3. Train from scratch?
My code is "fine-tune" the original SVD model, and if you don't want it, you can fix it by removing "from_pretrained" part.
